version: '3.4'

networks:
    # Network for communication between services
    backend:

volumes:
    sqlserver-data:
        driver: local

services:
    bbdd:
        container_name: dbContainer
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        #image: mcr.microsoft.com/mssql/server:2019-CU30-ubuntu-20.04  PARA CASA CON NUESTRA VERSIÓN.
        ports:
            - 1433:1433 # Never change the internal port!!!
        networks:
            - backend
        volumes:
            - sqlserver-data:/var/opt/mssql # Mounted volume in Docker
        environment:
            # More secure if you use an .env file
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=yourStrong(!)Password

    api:
        container_name: apiContainer
        image: restaurant_api:1.0
        ports:
            - 8001:80 # Never change the internal port!!!
        networks:
            - backend
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - bbdd # API without DB running is useless
        environment:
            # Connection string pointing to the database
            - ConnectionStrings__RestauranteDB=Server=localhost;Database=RestauranteDB;User Id=sa;Password=YourStrong@Passw0rd;
